import json
from pydantic import BaseModel
from litellm import completion
from cv_model import CVProfile


class FranceTravailQuery(BaseModel):
    keywords: str
    experience: str | None = None
    education_level: str | None = None
    region: str = "11"  # locked to Île-de-France for now, not generated by LLM


class _LLMQuery(BaseModel):
    """Internal model used only for LLM structured output — no region field."""
    keywords: str
    experience: str | None = None
    education_level: str | None = None


SYSTEM_PROMPT = """Tu es un expert en recherche d'emploi. À partir du profil CV fourni,
génère des paramètres optimaux pour une recherche d'offres d'emploi sur France Travail.

Pour le champ 'experience', utilise UNIQUEMENT ces valeurs (ou null si inconnu) :
- "1" : moins d'1 an d'expérience professionnelle
- "2" : 1 à 3 ans d'expérience
- "3" : plus de 3 ans d'expérience

Pour le champ 'education_level', utilise UNIQUEMENT ces valeurs, ou null si tu n'es pas
certain du niveau exact (préférer null plutôt qu'un filtre trop restrictif) :
- "NV3" : BAC+2 (BTS, DUT)
- "NV2" : BAC+3 ou BAC+4 (Licence)
- "NV1" : BAC+5 et plus (Master, Ingénieur, Doctorat)

Pour 'keywords', génère 2 à 4 mots-clés pertinents basés sur le poste visé et les
compétences techniques principales (ex: "AI Engineer Python LangGraph").
"""


def build_query(cv_profile: CVProfile, model: str = "ollama/qwen2.5:7b", api_key: str | None = None) -> FranceTravailQuery:
    """Generate France Travail search parameters from a CVProfile using a structured LLM call."""
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": json.dumps(cv_profile.model_dump(), ensure_ascii=False)},
    ]
    response = completion(
        model=model,
        messages=messages,
        response_format=_LLMQuery,
        temperature=0.1,
        api_key=api_key,
    )
    llm_result = _LLMQuery.model_validate_json(response.choices[0].message.content)
    return FranceTravailQuery(**llm_result.model_dump())
